### ISSUE TITLE
Force variant not working

### ISSUE THREAD

**Issue by Jordan-T** [dogchef-be/nuxt-goptimize#3]
I found an issue in the documentation.

To force a variant, we need to prefix it with `gopt_`

```js
const` key = `${COOKIE_PREFIX}_${experimentName}`;
```

**Comment by fabiofdsantos** [comment]
Do you mean forcing a variant via url query param?

**Comment by Jordan-T** [comment]
Sorry for the delay @fabiofdsantos, It's just in the readme:

```
Force a specific variant via url or param. E.g. url?experiment-x=1 or this.$exp('experiment-x', 1);
```

Should be `url?gopt_experiment-x=1` not `url?experiment-x=1`
